### ISSUE TITLE
bug: GKE – unable to build kubernetes objects from release manifest 

### ISSUE THREAD

**Issue by demoalex** [ydb-platform/ydb-kubernetes-operator#58]
# Bug Report

**YDB Kubernetes Operator version:**
helm list
```
CHART
operator-0.4.5

APP VERSION
0.4.9
```

**Environment**

GKE autopilot, GKE

cloud shell 
OS – Debian GNU/Linux 11 (bullseye)

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:58:47Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1503", GitCommit:"2c7bbda09a9b7ca78db230e099cf90fe901d3df8", GitTreeState:"clean", BuildDate:"2022-02-18T03:17:45Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

helm
```
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}
```

**Current behavior:**

I followed managed k8s steps here
https://ydb.tech/en/docs/deploy/orchestrated/yc_managed_kubernetes

```shell
helm repo add ydb https://charts.ydb.tech/
helm repo update
helm install ydb-operator ydb/operator
```

The last one produced this error
`Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "ServiceMonitor" in version "monitoring.coreos.com/v1"`

<img width="1309" alt="Screenshot_2022-04-20_at_15_35_56" src="https://user-images.githubusercontent.com/101798/164231690-5b759344-85d1-405e-a7f7-3d777bd7dd97.png">

**Comment by demoalex** [comment]
It's also same on my local machine (MacOS 10.15.7)
<img width="1114" alt="Screenshot 2022-04-20 at 16 36 03" src="https://user-images.githubusercontent.com/101798/164242920-02b173a3-cd23-445e-b098-a3d3bf25dd1a.png">

**Comment by demoalex** [comment]
somehow it stared to work fine after

```
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install v0.55.0 prometheus-community/kube-prometheus-stack
```
<img width="1100" alt="Screenshot_2022-04-20_at_16_50_59" src="https://user-images.githubusercontent.com/101798/164245942-d367ffeb-c14e-4b0a-b7c2-cf2f0685859e.png">

**Comment by bma13** [comment]
Hi Alex! We have changed default behavior of helm chart #59. Currently, ServiceMonitor is not installed by default and prometheus is not required.
