### ISSUE TITLE
feat: Support AdditionalAnnotations for storage and database reosource

### ISSUE THREAD

**Issue by avkviring** [ydb-platform/ydb-kubernetes-operator#63]
Hello

I am trying use linkerd for ydb, but it need add  annotations  "linkerd.io/inject: enabled"  to pods/deployments.

**Comment by bma13** [comment]
Hello

We have added "additionalAnnotations" to Storage and Database resources
To use it, you need update helm chart of operator up to 0.4.9 and apply crds from https://github.com/ydb-platform/ydb-kubernetes-operator/tree/master/deploy/ydb-operator/crds
